name: Run Telegram Bot

on:
  schedule:
    - cron: '0 */6 * * *'   # <-- Cron every 6 hours
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: true
    timeout-minutes: 360

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run 087.py
      run: |
        python 087.py
        
