name: Run 087 Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start bot
        env:
          TOKEN: ${{ secrets.TOKEN }}
          OWNER_ID: ${{ secrets.OWNER_ID }}
          ADMIN_ID: ${{ secrets.ADMIN_ID }}
          YOUR_USERNAME: ${{ secrets.YOUR_USERNAME }}
          UPDATE_CHANNEL: ${{ secrets.UPDATE_CHANNEL }}
        run: python 087.py
